services:
  postgres:
    image: postgres:16-alpine
    container_name: nest-person-photo-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_password
      POSTGRES_DB: nest_person_photo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: